# Config
# ========================================================================================

lang: fr

title: HATTA BELFAQIR

description: >
  Portfolio de développeur web présentant mes projets, mes compétences
  et mon évolution technique à travers des sites modernes, dynamiques
  et interactifs.

tagline: Développeur web · Frontend & Backend

keywords: []

logo: false

author:
  name: HATTA BELFAQIR
  email: hattab@example.com

menu:
  - title: Projets
    url: /projets/
  - title: À propos
    url: /about/
  - title: Contact
    url: /contact/

copyright: © 2024 HATTA BELFAQIR. Tous droits réservés.

permalink: /:categories/:year-:month-:day-:title/

paginate: 10
paginate_path: /:num/

theme: jekyll-theme-hydejack

# logo: /asset/img/mon-logo.png
# favicon: /asset/img/mon-favicon.png
# accent_image: /asset/img/mon-image-glace.jpg

accent_color: rgb(79,177,186)
theme_color: rgb(25,55,71)

defaults:
  - scope:
      path: asset/
    values:
      sitemap: false

hydejack:
  no_drawer: false
  no_navbar: false
  no_search: false
  no_break_layout: true
  no_large_headings: false
  advertise: false

collections:
  projects:
    permalink: /projects/:path/
    output: true

exclude:
  - .jekyll-cache
  - .sass-cache
  - vendor
  - Gemfile
  - Gemfile.lock

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
